# Generated by Django 4.1.3 on 2022-12-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PictureForRecognising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='recgnising/%Y/%m/')),
                ('recognised_text', models.TextField(blank=True, default='', null=True)),
                ('proccesed', models.BooleanField(default=False)),
            ],
        ),
    ]
