# Generated by Django 4.1.4 on 2022-12-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picturerecAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictureforrecognising',
            name='cleaned',
            field=models.ImageField(blank=True, null=True, upload_to='cleaning/%Y/%m/'),
        ),
    ]
