# Generated by Django 4.1.3 on 2022-12-02 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userint', '0002_pictureforrecongition'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PictureForRecongition',
        ),
    ]
