# Generated by Django 4.1.4 on 2022-12-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userint', '0004_pictureforrecongition'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictureforrecongition',
            name='rectangled_image',
            field=models.ImageField(blank=True, null=True, upload_to='rectangled/%Y/%m/%d'),
        ),
    ]
