# Generated by Django 4.1.3 on 2022-12-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userint', '0005_pictureforrecongition_rectangled_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictureforrecongition',
            name='cleaned_opencv_image',
            field=models.ImageField(blank=True, null=True, upload_to='cleaned/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='pictureforrecongition',
            name='rectangled_image',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='rectangled/%Y/%m/%d'),
        ),
    ]
