# Generated by Django 4.1.4 on 2022-12-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userint', '0007_pictureforrecongition_autoencoded_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictureforrecongition',
            name='should_be_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
